week_8/Blog_Task/mini_blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.index, name='index'),
    path("article-list/", views.ArticleListView.as_view(), name="article-list"),
    path("author-list/", views.AuthorListView.as_view(), name="author-list"),
    path("author/<int:pk>/", views.authordetails, name="author-details"),
    path("author/<int:pk>/update", views.authorupdate, name="update-author-details"),
    path("article/<slug:slug>/", views.articledetails, name="article-details"),
    path("article/<slug:slug>/comment/", views.CommentCreate.as_view(), name="article-comment"),
    path("article/<slug:slug>/comment/<int:pk>/delete", views.deletecomment, name="delete-comment"),
    path("article/<slug:slug>/comment/<int:pk>/restore", views.restorecomment, name="restore-comment"),
    path("article/<slug:slug>/delete/", views.deletearticle, name="delete-article"),
    path("article/<slug:slug>/restore", views.restorearticle, name="restore-article"),
    path("user/<str:username>/", views.userdetails, name="user-details"),
    path("user/<str:username>/update", views.userupdate, name="update-user-details"),
    path("user/<str:username>/delete", views.deleteuser, name="delete-user"),
    path("user/<str:username>/update/change-password", views.UpdatePassword.as_view(), name="change-password")
]

week_8/Blog_Task/mini_blog/mini_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from blog import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('NoBoneZ/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", RedirectView.as_view(url="blog/", permanent=True)),
    path("accounts/signup", views.create_user, name='signup'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

week_8/Blog_Task/mini_blog/blog/models.py
from django.utils.text import slugify
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect



# Create your models here.
class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_delete=False)

class DeleteManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_delete=True)


class Tags(models.Model):
    name_of_tag = models.CharField(max_length=15, help_text="Enter a suitable tag to help find the post",
                                   default="news")

    def __str__(self):
        return self.name_of_tag


class Niche(models.Model):
    name_of_niche = models.CharField(max_length=20, default="Entertainment",
                                     help_text="Kindly enter the Niche of your post")

    def __str__(self):
        return self.name_of_niche


class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    author_picture = models.ImageField(upload_to="author_images", null=True, blank=True)
    country = models.CharField(max_length=50)
    villain_story = models.TextField()
    date_of_registration = models.DateField(auto_now_add=True)

    # slug = models.SlugField(unique=True, null=False, blank=False)

    def __str__(self):
        return f" {self.lastname}, {self.firstname}"

    def get_absolute_url(self):
        return reverse("blog:author-details", args=[self.id])


class Article(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, help_text="Kindly input your name ", null=True)
    slug = models.SlugField(unique=True, null=False, blank=False)
    body = models.TextField()
    image = models.ImageField(upload_to="article_images", null=True, blank=True)
    date_uploaded = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)
    niche = models.ManyToManyField(Niche)
    tags = models.ManyToManyField(Tags, blank=True)
    is_delete = models.BooleanField(default=False)

    objects = models.Manager()
    active_objects = ActiveManager()
    deleted_objects = DeleteManager()


    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-date_uploaded"]
        unique_together = ["title", "author"]

    def save(self):
        self.slug = slugify(self.title)
        return super().save()

    def get_absolute_url(self):
        return HttpResponseRedirect(reverse("blog:article-details", args=[self.slug]))

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, editable=False, null=True)
    comment = models.TextField()
    date_of_comment = models.DateTimeField(auto_now_add=True)
    commenter_name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, editable=False)
    is_delete = models.BooleanField(default=False)

    objects = models.Manager()
    active_objects = ActiveManager()
    deleted_objects = DeleteManager()

    class Meta:
        ordering = ["-date_of_comment"]
        unique_together = ["article", "comment", "commenter_name"]

    def __str__(self):
        return f"{self.date_of_comment}"

    def comment_description(self):
        return self.comment[:50]

week_8/Blog_Task/mini_blog/blog/forms.py
from django import forms
from .models import Comment, User, Author


class CommentOnArticle(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["date_of_comment", "is_delete"]


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password"]


class UpdateAuthor(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"

class UpdateUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email" ]

class ChangePassword(forms.Form):
    password = forms.PasswordInput()

week_8/Blog_Task/mini_blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Author, Article, Niche, Comment, User
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView, UpdateView
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse
from .forms import CommentOnArticle, CreateUserForm, UpdateAuthor, UpdateUser, ChangePassword
from django.contrib.auth.hashers import make_password
from django.contrib import messages
# from django.core import serializers
from django.db.models import Q

# Create your views here.


def index(request):
    num_articles = Article.active_objects.all().count()
    num_authors = Author.objects.all().count()
    num_niches = Niche.objects.all().count()
    num_users = User.objects.filter(is_staff=False).count()

    context = {"num_articles": num_articles,
               "num_authors": num_authors,
               "num_niches": num_niches,
               "num_users": num_users}
    return render(request, "blog/index.html", context)


class ArticleListView(ListView):
    model = Article
    queryset = Article.active_objects.all()
    context_object_name = "article_list"
    template_name = "blog/article_list.html"
    paginate_by = 5


class AuthorListView(LoginRequiredMixin, ListView):
    model = Author
    template_name = "blog/author_list.html"
    queryset = Author.objects.all()
    context_object_name = 'author_list'


@login_required
def authordetails(request, pk):
    author = get_object_or_404(Author, pk=pk)
    active_articles = Article.active_objects.filter(author=author)
    deleted_articles = Article.deleted_objects.filter(author=author)
    context = {"author": author,
               "active_articles": active_articles,
               "deleted_articles": deleted_articles}

    return render(request, "blog/author_details.html", context)


@login_required
def articledetails(request, slug):
    article = Article.active_objects.get(slug=slug)
    all_comments = Comment.objects.filter(article=article)
    active_comments = Comment.active_objects.filter(article=article)
    deleted_comments = Comment.deleted_objects.filter(article=article)

    if request.method == "GET":
        comment_form = CommentOnArticle()
        context = {"article": article,
                   "comment_form": comment_form,
                   "all_comments": all_comments,
                   "deleted_comments": deleted_comments,
                   "active_comments": active_comments}
        return render(request, "blog/article_details.html", context)
    # else:
    #     return JsonResponse({"error": "Error occured"}, status=400)
    else:
        # comment_form = CommentOnArticle(request.POST)
            comment = request.POST["comment"]
            print(comment)
            print("Got Here")
            print(request.user.username)
            user = User.objects.get(username=request.user.username)
            comment = Comment.objects.create(comment=comment,article=Article.objects.get(slug=slug),commenter_name=user)
            comment.save()
            print("Got Here 2 ")
            response = {
                "comment_commenter_name":comment.commenter_name,
                "comment_comment":comment.comment,
                "comment_article":comment.article,
            }
            print("Responded")
            return JsonResponse(response,content_type="Application/json")
            # return HttpResponseRedirect(reverse("blog:article-details", args=[article.slug]))
        #     serialize_comment = serializers.serialize('json', [comment])
        #     return JsonResponse({"comment": serialize_comment}, status=200)
        # else:
        #     return JsonResponse({"error": "Error occured"}, status=400)



class CommentCreate(View):
    def get(self, request, slug):
        comment_form = CommentOnArticle()
        context = {
            "comment_form": comment_form
        }

        return render(request, "blog/comment_form.html", context)

    def post(self, request, slug):
        comment_form = CommentOnArticle(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = Article.objects.get(slug=slug)
            comment.commenter_name = self.request.user
            comment.save()
            return HttpResponseRedirect(reverse("blog:article-details", args=[slug]))

        context = {
            "comment-form": comment_form,
        }
        return render(request, "blog/comment_form.html", context)


def create_user(request):
    if request.method == "GET":
        user_form = CreateUserForm()
        context = {"user_form": user_form}

        return render(request, "registration/signup.html", context)

    elif request.method == "POST":
        user_form = CreateUserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.password = make_password(user_form.cleaned_data["password"])
            user.save()

        return HttpResponseRedirect(reverse("login"))

@login_required()
def authorupdate(request,pk):
    author = Author.objects.get(id=pk)
    form = UpdateAuthor(instance=author)

    if request.method =="POST":
        form = UpdateAuthor(request.POST, request.FILES, instance=author)

        if form.is_valid():
            updated_author = form.save(commit=False)
            updated_author.author_picture = form.cleaned_data["author_picture"]
            updated_author.save()
            # form.save()
            return HttpResponseRedirect(author.get_absolute_url())

    elif request.method == "GET":
        context = {"form": form}
        return render(request, "blog/user_update_form.html", context)

class UpdatePassword(View):
    def get(self, username):
        print(username)
        form = ChangePassword()

        context = {"form": form}
        return render(request, "blog/change_password.html", context)

    def post(self, username):
        user = User.objects.get(username=username)
        password_form = ChangePassword(request.POST)

        if password_form.is_valid():
            user.password = make_password(password_form.cleaned_data["password"])
            user.save()
            return HttpResponseRedirect(reverse("blog:user-details", args=[username]))


@login_required()
def userdetails(request, username):
    user = User.objects.get(username=username)
    context = {"user" : user}

    return render(request, "blog/user_details.html", context)

@login_required()
def userupdate(request,username):
    user = get_object_or_404(User, username=username)
    form = UpdateUser(instance=user)

    if request.method == "POST":
        form = UpdateUser(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("blog:user-details", args=[username]))

    context = {"form":form}
    return render(request, "blog/user_update_form.html", context)

@login_required()
def deleteuser(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == "POST":
        user.is_active = False
        user.save()
        return redirect("blog:index")

    context = {"obj" : user}
    return render(request,"blog/delete.html", context)


@login_required()
def deletearticle(request, slug):
    article = get_object_or_404(Article, slug=slug)

    if request.method == "POST":
        article.is_delete = True
        article.save()
        return HttpResponseRedirect(reverse("blog:author-details", args=[article.author.id]))

    context = {"obj": article}
    return render(request, "blog/delete.html", context)

@login_required()
def restorearticle(request, slug):
    article = get_object_or_404(Article, slug=slug)

    if request.method == 'POST':
        article.is_delete = False
        article.save()
        return HttpResponseRedirect(reverse("blog:author-details", args=[article.author.id]))

    context = {"obj" : article}
    return render(request, "blog/restore.html", context)


@login_required()
def deletecomment(request, slug, pk):
    comment = get_object_or_404(Comment, id=pk)
    # article = Articles.active_objects.filter()
    if request.method == "POST":
        comment.is_delete = True
        comment.save()
        return HttpResponseRedirect(reverse("blog:article-details", args=[slug]))

    context = {"obj": comment.comment_description()}
    return render(request, "blog/delete.html", context)

def restorecomment(request, slug, pk):
    comment = get_object_or_404(Comment,id=pk)
    if request.method == "POST":
        comment.is_delete = False
        comment.save()
        return HttpResponseRedirect(reverse("blog:article-details", args=[slug]))

    context = {"obj" : comment.comment_description()}
    return render(request, "blog/restore.html", context)

week_8/Blog_Task/mini_blog/blog/templates/blog/article_details.html
{% extends "base_generic.html" %}


{% block title %}
<title>{{article}}</title>
{% endblock %}


{% block content %}
<h1>{{article.title.capitalize}}</h1>
<p>by <a href="{% url 'blog:author-details' article.author.id %}">{{article.author}}</a></p>
<p><strong>Post date : {{article.date_uploaded}}</strong></p>
<br>
<p><strong>Update date: {{article.date_updated}}</strong></p>
<br>
<hr>
<h3>Description</h3>


{% if article.image %}
    <img src="{{article.image.url}}" alt="{{article.title}} image">
{% endif %}
<p>{{article.body}}</p>


<br>
<br>
<br>
<br>
<br>


<h3>Comments</h3>
<hr>
{% if user.is_authenticated and not user.is_staff %}
    {% for comment in active_comments %}
        <p><strong>{{comment.comment}}</strong></p>
        <p>by {{comment.commenter_name}} on {{comment.date_of_comment | timesince}}</p>
        <hr>
    {% endfor %}

{% elif user.is_staff %}
    <div class="all_comments">
     {% for comment in all_comments %}
        <p><strong>{{comment.comment}}</strong></p>
        <p>by {{comment.commenter_name}} on {{comment.date_of_comment | timesince}}
                {% if user.first_name == article.author.firstname and user.last_name == article.author.lastname and not comment.is_delete %}
        ---<small><a href="{% url 'blog:delete-comment' article.slug comment.id  %}">Delete Comment</a></small>{% endif %}
        </p>

        {% if comment.is_delete %}
                <p><em>Deleted</em></p>
                        {% if user.first_name == article.author.firstname and user.last_name == article.author.lastname %}
                                <small><a href="{% url 'blog:restore-comment' article.slug comment.id%}">Restore Comment</a></small>
                        {% endif %}
        {% else %}
                 <p><em>Active</em></p>
        {% endif %}
        <hr>
    {% endfor %}
        </div>

{% endif %}




<h3>Post Your comment</h3>
<form method="POST" id="comment-form">
{% csrf_token %}
    {{comment_form.as_p}}
<input type="submit"  id="submit-comment" value="Submit">
</form>
<hr>




<!--<script type="text/javascript" charset="utf-8" >-->
<!--    $(document).on('submit','#comment-form',function(e) {-->
<!--        e.preventDefault();-->
<!--        var serializedData = $(this).serialize();-->
<!--        console.log('Javascript @@@@');-->

<!--        $.ajax({-->
<!--            type:'POST',-->
<!--            url:'{% url "blog:article-details" article.slug %}',-->
<!--            data: serializedData,-->
<!--            success: function(response) {-->
<!--                alert("sucess");-->
<!--                let comment = JSON.parse(response["comment"])-->
<!--                let fields = comment[0]["fields"]-->

<!--                $(".all_comments").prepend(-->
<!--                    `-->
<!--                    <p><strong>$(fields["comment"])</strong></p>-->
<!--                    <p>by $(fields["commenter_name"])  on $(fields["date_of_comment"])</p>-->
<!--                    `-->
<!--                )-->
<!--            })-->
<!--        });-->
<!--  </script>-->


<script src="https://code.jquery.com/jquery-3.5.1.js"
          integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
<script type="text/javascript" charset="UTF-8">
    $(document).on("submit", "#comment-form", function(e) {
        e.preventDefault();
            console.log("Got Heree !!!!")
        $.ajax({
            type:"POST",
            url:"{% url 'blog:article-details' article.slug %}",
            data:{
                comment:$("#id_comment").val(),
                csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val(),
            },
            success:function(e){
                console.log(e)

             },

        });

    });



</script>
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/article_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Articles List</h1>
    {% if article_list %}
        <ul>
        {% for article in article_list %}
        <li><a href="{% url 'blog:article-details' article.slug %}">{{article}}</a> by <a href="{% url 'blog:author-details' article.author.id %}">{{article.author}}</a> on {{article.date_uploaded}}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No articles uploaded Yet</p>
    {% endif %}
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/author_details.html
{% extends "base_generic.html" %}

{% block title %}
<title>{{author}}</title>
{% endblock %}

{% block content %}
<h1>{{author}}</h1>
{% if author.author_picture %}
<img src="{{author.author_picture.url}}" alt ='author profile picture'>
{% endif %}

<ul>
  <li>Country: {{author.country}}</li>
  <li>Date of employment: {{author.date_of_registration}}</li>
</ul>
<br>


{% if active_articles.all.count > 0 %}
  <h4>Articles Written</h4>
    {% for article in active_articles.all %}
    <ul>
      <li><a href="{% url 'blog:article-details' article.slug %}">{{article}}</a>  written on {{article.date_uploaded}}</li>
        {% if user.is_staff and user.first_name == article.author.firstname and user.last_name == article.author.lastname %}
      <a href="{% url 'blog:delete-article' article.slug %}"><small>DELETE ARTICLE</small></a>
          {% endif %}
    </ul>
    {% endfor%}
{% else %}
<p>No Articles Written Yet</p>
{% endif %}



{% if user.is_staff %}
<h4>Deleted Articles</h4>
  {% if deleted_articles.all.count > 0 %}
    {% for article in deleted_articles.all %}
      <ul>
        <li>{{article}}</li>
        {% if user.is_staff and user.first_name == article.author.firstname and user.last_name == article.author.lastname %}
        <small><a href="{% url 'blog:restore-article' article.slug %}">Restore Article</a></small>
        {% endif %}
      </ul>
      {% endfor %}
  {% else %}
    <p>No deleted articles</p>
  {% endif %}
{% endif %}



{% if user.is_staff and user.first_name == author.firstname and user.last_name == author.lastname%}
<hr>
<a href="{% url 'blog:update-author-details' author.id %}">UPDATE PROFILE</a>
{% endif %}
<hr>
<h4>Bio</h4>
<p>{{author.villain_story}}</p>
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author List</h1>
    {% if author_list %}
        {% for author in author_list %}
            <ul>
                <li><a href="{% url 'blog:author-details' author.id %}">{{author}}</a> from {{author.country}}</li>
            </ul>
        {% endfor %}
    {% else %}
        <p>There are currently no authors</p>
    {% endif %}
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/change_password.html
{% extends "base_generic.html" %}


{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <p>{{form.as_p}}</p>

</form>
{% endblock%}

week_8/Blog_Task/mini_blog/blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Post Your comment</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ comment_form }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/delete.html
{% extends 'base_generic.html' %}


{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>

    <input type="submit" value="Submit">
</form>
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/index.html
{% extends "base_generic.html" %}


<head>
  {% block title %}<title>Koder Black's Mini Blog </title>{% endblock %}
</head>
{% block content %}
  <h1>Mini-Blog</h1>
  <p>Welcome to Koder's Blog, a Blog developed by <em>47</em>!</p>
  <h2>Descriptive History</h2>
  <p>This blog was developed by 47, as a task, isssued during the ATS program. To develop the blog, previous knowledge on different aspect of the django packages would need to be implemented. Presently the blog has, </p>
  <ul>
    <li><strong>Articles:</strong> {{ num_articles }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Niches:</strong> {{num_niches}}</li>
    <li><strong>Number Of Users:</strong> {{num_users}}</li>
  </ul>

{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/restore.html
{% extends 'base_generic.html' %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <p>Are you sure you want to restore "{{obj}}" ?</p>
  <a href="{{request.META.HTTP_REFERER}}">Go back</a>
  <input type="submit" value="Confirm">

</form>
{% endblock %}

week_8/Blog_Task/mini_blog/blog/templates/blog/user_details.html
{% extends "base_generic.html" %}


{% block content %}
<h1>{{user| title}}</h1>
<p><strong>Username:</strong>   {{user.username}}</p>
<p><strong>Firstname:</strong>   {{user.first_name}}</p>
<p><strong>Lastname:</strong>   {{user.last_name}}</p>
<p><strong>Email:</strong>   {{user.email}}</p>

<a href="{% url 'blog:change-password' user.username %}">Change password</a>
<hr>
<a href="{% url 'blog:update-user-details' user.username %}">EDIT PROFILE</a>
<hr>
<h3><a href="{% url 'blog:delete-user' user.username %}">DELETE PROFILE</a></h3>
{% endblock%}

week_8/Blog_Task/mini_blog/blog/templates/blog/user_update_form.html
{% extends "base_generic.html" %}

{% block title %}
<title>Update Form</title>
{% endblock %}

{% block content %}
<h1>Update your details</h1>
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{form.as_p}}
  </table>
  <input type="submit" value="Update">
</form>
{% endblock %}